### ISSUE TITLE
Separate section for libraries?

### ISSUE THREAD

**Issue by larsnaesbye** [barbeau/awesome-gnss#11]
Right now software libraries are under Desktop, if giulioscattolin/google-gnss-logger is anything to go by.

If I wanted to add, say, https://github.com/stenseng/ntripstreams  - shouldn't this be under a libraries section?

**Comment by barbeau** [comment]
Yes, I'm fine splitting out libraries into their own section - what you say makes sense. Pull requests welcome! :)
