### ISSUE TITLE
Desktop tools are not sorted in open source and proprietary

### ISSUE THREAD

**Issue by gdt** [barbeau/awesome-gnss#4]
I realize that it can be figured out, but as part of the grand struggle it would be nice to reorg into an open source and a proprietary section so it's clearer.

**Comment by barbeau** [comment]
@gdt Agreed. I think it started small so I didn't divide it, but now it's grown and could be better organized. Contributions welcome if someone else gets to it before me :).

**Comment by barbeau** [comment]
Fixed in https://github.com/barbeau/awesome-gnss/commit/d760f71a9485ac74d4e9ccc7404eb8f933248494
