### ISSUE TITLE
GFZRNX - RINEX GNSS Data Conversion and Manipulation Toolbox

### ISSUE THREAD

**Issue by aewallin** [barbeau/awesome-gnss#5]
https://dataservices.gfz-potsdam.de/panmetaworks/showshort.php?id=escidoc:1577894

I've used it for RINEX v3->v2 conversion and concatenating multiple RINEX files into one - but it can do many other things also.
maybe a bit similar to teqc - but teqc is no longer maintained..

**Comment by barbeau** [comment]
Added in https://github.com/barbeau/awesome-gnss/commit/0fe950bb57a01f5064c20a879967d709d490ad43. Thanks @aewallin!
